"package:docgen":
  - changed-files:
      - any-glob-to-any-file:
          - "packages/svelte-docgen/**"

"package:extractor":
  - changed-files:
      - any-glob-to-any-file:
          - "packages/extractor/**"

"package:vite-plugin":
  - changed-files:
      - any-glob-to-any-file:
          - "packages/vite-plugin-svelte-docgen/**"

"package:server":
  - changed-files:
      - any-glob-to-any-file:
          - "packages/server/**"

"app:docs":
  - changed-files:
      - any-glob-to-any-file:
          - "apps/docs/**"

"documentation":
  - changed-files:
      - any-glob-to-any-file:
          - "**/README.md"

"ci/cd":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"
