# https://pnpm.io/pnpm-workspace_yaml
---
packages:
    - "packages/*"

# https://pnpm.io/catalogs
catalog:
    "dts-buddy": "^0.5.0"
    "svelte": "^5.3.0"
    "typescript": "^5.7.0"
    "vite": "^6.0.0"
