# https://pnpm.io/pnpm-workspace_yaml
---
packages:
  - "packages/*"
  - "apps/*"

# https://pnpm.io/catalogs
catalog:
  "svelte": "^5.19.0"
  "dts-buddy": "^0.5.4"
  "typescript": "^5.7.3"
  "valibot": "^1.0.0-beta.12"
  "vite": "^6.0.7"
