name: CI
# NOTE: CI -> Continuous Integration

on:
  pull_request:
    branches: [main, next]
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches: [main, next]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CI: true

permissions:
  contents: write
  id-token: write
  pages: write
  pull-requests: write

jobs:
  lint_biome:
    name: Lint
    uses: ./.github/workflows/biome.yml

  lint_prettier:
    name: Lint
    uses: ./.github/workflows/prettier.yml

  lint_tsc:
    name: Lint
    uses: ./.github/workflows/tsc.yml

  lint_typos:
    name: Lint
    uses: ./.github/workflows/typos.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml

  publish_preview:
    name: Publish
    uses: ./.github/workflows/preview.yml
    needs: [lint_biome, lint_prettier, lint_tsc, lint_typos, test]

  publish_typedoc:
    name: Publish
    uses: ./.github/workflows/typedoc.yml
    needs: [lint_biome, lint_prettier, lint_tsc, lint_typos, test]
    with:
      type: ${{ github.event_name == 'pull_request' && contains(fromJson('["opened", "reopened", "synchronize"]'), github.event.action) && 'pr-preview' || 'deploy' }}
