name: ESLint

on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CI: true

permissions:
  contents: read
  pull-requests: write

jobs:
  eslint:
    name: ESLint
    runs-on: macos-latest
    timeout-minutes: 1
    steps:
      # https://github.com/actions/checkout
      - name: Checkout to the repository
        uses: actions/checkout@v4

      # https://github.com/reviewdog/action-eslint
      - name: Run ESLint to review
        uses: reviewdog/action-eslint@v1
        with:
          fail_level: warning
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
